camera_chains:
  - sensor_id: left
    camera_id: left
    chain:
        before_chain: [ base_footprint, torso_0_link ]
        chain_id: torso_chain
        links: [torso_0_link, torso_upper_neck_tilt_link]
        after_chain: [ head_axis_link, head_color_camera_l_link ]
  - sensor_id: kinect_rgb
    camera_id: kinect_rgb
    chain:
        before_chain: [ base_footprint, torso_0_link ]
        chain_id: torso_chain
        after_chain: [ head_axis_link, head_cam3d_link ]
        links: [torso_0_link, torso_upper_neck_tilt_link]

chains:
  - sensor_id:    arm_chain
    chain_id:     arm_chain
    after_chain:  [sdh_palm_link, arm_cb ]
    links: [arm_0_link, arm_7_link]

