dh_chains:
    torso_chain:
        cov:
            joint_angles: [ 0.01, 0.01, 0.01 ]
                
    arm_chain:
        cov:
            joint_angles: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]
            
 
transforms:
    # specified as x,y,z translation and rotation vector (angle = magnitude, direction = vector)!
    base_footprint: [ 0, 0, 0, 0, 0, 0 ]                                                                                           # base_link -> base_footprint                                    # in urdf
    arm_cb:               [ -0.12, 0.02, 0.1, pi/2, 0, 0 ]                                                                      # arm_7_link -> calibration_pattern
    
    head_axis_link:      [ 0, .173, 0, 0, 0, 0 ]                                                  # rpy: (0, 0, 0)                 # torso_upper_neck_tilt_link -> head_axis_link             # in urdf
    head_color_camera_l_link: [ 0, 0, -0.06, 0, -pi/2, 0]                                         # rpy: (pi, -pi/2, pi)          # head_axis_link -> head_color_camera_l_link                # in urdf
    head_color_camera_r_link: [ 0, 0,  0.06, 0, -pi/2, 0]                                        # rpy: (pi, -pi/2, pi)          # head_axis_link -> head_color_camera_r_link                # in urdf
    head_color_camera_l_frame_link: [ 0, 0, 0, 1.20919958, -1.20919958,  1.20919958 ]            # rpy: (-pi/2, -pi/2, -pi)      # head_color_camera_l_link -> head_color_camera_l_frame        # in urdf
    head_cam3d_frame: [ -0.002, -0.030, 0.020, 0, -pi/2, 0 ]                                # rpy: (0, -pi/2, 0)            # head_color_camera_l_link -> head_cam3d_frame                # in urdf
    
    torso_0_link:        [ 0.155, 0, 0.892, pi/2, 0, 0]                                          # rpy: (pi/2, 0, 0)             # base_link -> torso_0_link                        # in urdf
    arm_0_link:          [-0.015982, -0.080992, 0.875995, 0.78081498, -0.10279649, -0.24817203 ] # rpy: (0.7854, 0.0, -0.2618)   # base_link -> arm_0_link                        # in urdf
    
rectified_cams:
    left:
        baseline_shift: 0.0
        f_shift: 0.0
        cx_shift: 0.0
        cy_shift: 0.0
        cov: {u: 0.125, v: 0.125}
    right:
        baseline_shift: 0.0
        f_shift: 0.0
        cx_shift: 0.0
        cy_shift: 0.0
        cov: {u: 0.125, v: 0.125}
    kinect_rgb:
        baseline_shift: 0.0
        f_shift: 0.0
        cx_shift: 0.0
        cy_shift: 0.0
        cov: {u: 0.25, v: 0.25}    

checkerboards:
    cb_9x6:
      corners_x: 9
      corners_y: 6
      spacing_x: .03
      spacing_y: .03
